### ISSUE TITLE
start gero failed

### ISSUE THREAD

**Issue by lynAzrael** [sero-cash/go-sero#11]
[root@ecs-s6-large-2-linux-20190824161429 geropkg]# gero console
start libczero 1 ...

                            
                         sssSSssss
                   sSSSSSSSSSSSSSSSSSSSs
               sSSSSSSSSSSSSSSSSSSSSSSSSSSs
             sSSSSSSss               ssSSSSSSs
          ssSSSSSSs        s sss        sSSSSSSs
         sSSSSSs     sSSSSSSSSSSSSSSs      sSSSSS
        sSSSS     +SSSSSSS+        sSSSsss   SSSSSs
      sSSSSs   sSSSSSSSs   sssSss      SSSS    sSSSS
      SSSS     SSSSSs     sSSSSSSSSs   sSSSSs   sSSSSs
    sSSSS    sSSSSSs     SSSSSSSSSSSs   SSSSSs    SSSSs
    SSSSs    SSSSSS     SSSSSSSSSSSSSs  SSSSSSSs   SSSS
   SSSSs    SSSSSSs    sSSSSSSSSSSSSSSs SSSSSSSSs  sSSSs
  sSSSs     SSSSSSs      SSSSSSSSSSSSSssSSSSSSSSSs  +SSSs
  SSSS      SSSSSSs      sSSSSSSSSS+SSSSSSSSSSSSSS  sSSSS
 sSSSs      SSSSSS         sSSSSSSSSSSsSSSSSSSSSSSs ssSSS
 sSSSs  s   SSSSSSs           SSSSSSSSSSssSSSSSSSSS   SSSs
 SSSS  sS    SSSSSSs             SSSSSSSSSs sSSSSSS   SSSs
 SSSss sSs   sSSSSSSs             ssSSSSSSSS  sSSSS   SSSs
 SSS+s SSS    sSSSSSSS               sSSSSSSS ssSSS   SSSS
 SSSSs sSSSs    sSSSSSSSss             sSSSSSSs SSS   SSSs
 SSSS  sSSSSS     SSSSSSSSSs            sSSSSSSs SS   SSS+
 SSSSs  SSSSSSS     sSSSSSSSSS            SSSSSs ss   SSSs
  SSS+  sSSSSSSSSSs   sSSSSSSSSSs         SSSSSS ss  +SSS
  SSSS   SSSSSSSSSSSss   sSSSSSSSs        sSSSSS    sSSSS
  sSSSs  sSSSSSSSs sSSSs   sSSSSSSs       SSSSSs    sSSSs
   SSSSs  sSSSSSSs  SSSSSSs sSSSSSSs      SSSSSs   sSSS+
    SSSS    SSSSS+   SSSSSSSssSSSSSs     sSSSS    sSSSS
    sSSSS    SSSSS   ssSSSSSSsSSSSss    sSSSSs    SSSS
      SSSSss   SSSs     SSSSSSSSSs     SSSSS    sSSSSs
       SSSSs    sSSs      +SSSSS     sSSSSs   ssSSSs
        sSSSSS    sSSSS           sSSSSs     SSSSSs
          SSSSS+ss     sSSSSSSSSSSSS      sSSSSSs
            SSSSSSss                   ssSSSSSSs
             sSSSSSSSsss           ssSSSSSSSS
                sSSSSSSSSSSSSSSSSSSSSSSSSSs
                   ssSSSSSSSSSSSSSSSSSs
                          rrssssrr

zero init ...
***CZERO*** nettype : 2
***CZERO*** b_path : /lib64
***CZERO*** account_dir : /root/.sero/keystore
load keypair from: /data/output
terminate called after throwing an instance of 'std::runtime_error'
  what():  load path failed: /data/output/vk.bin
SIGABRT: abort
PC=0x7f389f7d4207 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f389f7d4207
stack: frame={sp:0x7ffd27872d08, fp:0x0} stack=[0x7ffd27074d48,0x7ffd27873d70)
00007ffd27872c08:  00007f389eed8611  00007ffd278728a0 
00007ffd27872c18:  0000002200000003  00007ffd27872810 
00007ffd27872c28:  0000001100000001  00007ffd00000000 
00007ffd27872c38:  00007ffd278728a0  00007ffd00000003 
00007ffd27872c48:  00007ffd27873cb0  6e75723a3a647473 
00007ffd27872c58:  7272655f656d6974  00007ffd2700726f 
00007ffd27872c68:  000000000046d420 <runtime.asmcgocall+112>  0000000000000000 
00007ffd27872c78:  0000000000000000  0000000000000000 
00007ffd27872c88:  00007f38a00d2de0  4000000000000000 
00007ffd27872c98:  0000000000000000  0000000000000000 
00007ffd27872ca8:  0000000000000000  0000000000000000 
00007ffd27872cb8:  0000000000000000  0000000000000000 
00007ffd27872cc8:  0000000000000000  0000000000000000 
00007ffd27872cd8:  00007f389fb65868  000000000372c838 
00007ffd27872ce8:  000000000372c9d0  00007ffd27872ec0 
00007ffd27872cf8:  000000000372b2a0  00007ffd278730f0 
00007ffd27872d08: <00007f389f7d58f8  0000000000000020 
00007ffd27872d18:  0000000000000000  0000000000000000 
00007ffd27872d28:  0000000000000000  0000000000000000 
00007ffd27872d38:  0000000000000000  0000000000000000 
00007ffd27872d48:  0000000000000000  0000000000000000 
00007ffd27872d58:  0000000000000000  0000000000000000 
00007ffd27872d68:  0000000000000000  0000000000000000 
00007ffd27872d78:  0000000000000000  0000000000000000 
00007ffd27872d88:  0000000000000000  00007f389fb651c0 
00007ffd27872d98:  00007f389f88cff9  0000000000000000 
00007ffd27872da8:  00007f389f8180b3  000000000372c838 
00007ffd27872db8:  00007f389fb651c0  0000000000000001 
00007ffd27872dc8:  00007f389fb65243  00007f389fb613a0 
00007ffd27872dd8:  00007f389f8198ce  00007f389fb651c0 
00007ffd27872de8:  000000000000000a  000000000372c9d0 
00007ffd27872df8:  00007ffd27872ec0  000000000372b2a0 
runtime: unknown pc 0x7f389f7d4207
stack: frame={sp:0x7ffd27872d08, fp:0x0} stack=[0x7ffd27074d48,0x7ffd27873d70)
00007ffd27872c08:  00007f389eed8611  00007ffd278728a0 
00007ffd27872c18:  0000002200000003  00007ffd27872810 
00007ffd27872c28:  0000001100000001  00007ffd00000000 
00007ffd27872c38:  00007ffd278728a0  00007ffd00000003 
00007ffd27872c48:  00007ffd27873cb0  6e75723a3a647473 
00007ffd27872c58:  7272655f656d6974  00007ffd2700726f 
00007ffd27872c68:  000000000046d420 <runtime.asmcgocall+112>  0000000000000000 
00007ffd27872c78:  0000000000000000  0000000000000000 
00007ffd27872c88:  00007f38a00d2de0  4000000000000000 
00007ffd27872c98:  0000000000000000  0000000000000000 
00007ffd27872ca8:  0000000000000000  0000000000000000 
00007ffd27872cb8:  0000000000000000  0000000000000000 
00007ffd27872cc8:  0000000000000000  0000000000000000 
00007ffd27872cd8:  00007f389fb65868  000000000372c838 
00007ffd27872ce8:  000000000372c9d0  00007ffd27872ec0 
00007ffd27872cf8:  000000000372b2a0  00007ffd278730f0 
00007ffd27872d08: <00007f389f7d58f8  0000000000000020 
00007ffd27872d18:  0000000000000000  0000000000000000 
00007ffd27872d28:  0000000000000000  0000000000000000 
00007ffd27872d38:  0000000000000000  0000000000000000 
00007ffd27872d48:  0000000000000000  0000000000000000 
00007ffd27872d58:  0000000000000000  0000000000000000 
00007ffd27872d68:  0000000000000000  0000000000000000 
00007ffd27872d78:  0000000000000000  0000000000000000 
00007ffd27872d88:  0000000000000000  00007f389fb651c0 
00007ffd27872d98:  00007f389f88cff9  0000000000000000 
00007ffd27872da8:  00007f389f8180b3  000000000372c838 
00007ffd27872db8:  00007f389fb651c0  0000000000000001 
00007ffd27872dc8:  00007f389fb65243  00007f389fb613a0 
00007ffd27872dd8:  00007f389f8198ce  00007f389fb651c0 
00007ffd27872de8:  000000000000000a  000000000372c9d0 
00007ffd27872df8:  00007ffd27872ec0  000000000372b2a0 

goroutine 28 [syscall]:
runtime.cgocall(0xcbad80, 0xc420050fa0, 0x14)
	/root/go/src/runtime/cgocall.go:128 +0x64 fp=0xc420050f70 sp=0xc420050f38 pc=0x415484
github.com/sero-cash/go-czero-import/cpt._Cfunc_zero_init(0x2f53450, 0x2)
	_cgo_gotypes.go:265 +0x45 fp=0xc420050fa0 sp=0xc420050f70 pc=0x6c4b95
github.com/sero-cash/go-czero-import/cpt.ZeroInit.func1(0xc420038320, 0x14, 0xc420084302)
	/root/gopath/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:58 +0x4c fp=0xc420050fc8 sp=0xc420050fa0 pc=0x6c84ac
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420050fd0 sp=0xc420050fc8 pc=0x46e751
created by github.com/sero-cash/go-czero-import/cpt.ZeroInit
	/root/gopath/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:57 +0x52

goroutine 1 [chan receive]:
github.com/sero-cash/go-czero-import/cpt.ZeroInit(0xc420038320, 0x14, 0x2, 0x0, 0xc4203cba00)
	/root/gopath/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:64 +0x6b
main.init.0.func1(0xc4200f8000, 0x1681180, 0xc4200c04e0)
	/root/gopath/src/github.com/sero-cash/go-sero/cmd/gero/main.go:223 +0x60b
github.com/sero-cash/go-sero/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200c04e0, 0xc4200b2000, 0x2, 0x2, 0x0, 0x0)
	/root/gopath/src/github.com/sero-cash/go-sero/vendor/gopkg.in/urfave/cli.v1/app.go:241 +0x6f0
main.main()
	/root/gopath/src/github.com/sero-cash/go-sero/cmd/gero/main.go:347 +0xad

goroutine 20 [chan receive]:
github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc4200ce180, 0xc4200ce0c0)
	/root/gopath/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
created by github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/root/gopath/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xf2

goroutine 21 [chan receive]:
github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc4200ce180, 0xc4200ce120)
	/root/gopath/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x7b
created by github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
	/root/gopath/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x11e

goroutine 22 [syscall]:
os/signal.signal_recv(0x0)
	/root/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/root/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/root/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 7 [select, locked to thread]:
runtime.gopark(0x1681e18, 0x0, 0xf5106f, 0x6, 0x18, 0x1)
	/root/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420076f50, 0xc42008e2a0)
	/root/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/root/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/root/go/src/runtime/asm_amd64.s:2361 +0x1

rax    0x0
rbx    0x7f389fb65868
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x4abb
rsi    0x4abb
rbp    0x372c838
rsp    0x7ffd27872d08
r8     0xa
r9     0x7f38a0588800
r10    0x8
r11    0x206
r12    0x372c9d0
r13    0x7ffd27872ec0
r14    0x372b2a0
r15    0x7ffd278730f0
rip    0x7f389f7d4207
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

what(): load path failed: /data/output/vk.bin
How to create this file ?

**Comment by lynAzrael** [comment]
what(): load path failed: /data/output/vk.bin
