### ISSUE TITLE
Error: lstate.balance is no longer supported

### ISSUE THREAD

**Issue by lanceyan** [sero-cash/go-sero#20]
I follow this text  "from-the-sourcecode-base-on-centos7.md".

And when i excute  "build/bin/gero  --datadir "./sero-data" console" , the error is throwed.

> personal.newAccount("123")
"5KXJF5rDjuuzLuFQELrKAuSypRWHCgcJf7YrCmkoj8ALiLiyY13Pn6zjUBY54EqyDF8pvEL4bhE67RvQePgd7Nd3"

> sero.getBalance(sero.accounts[0])
Error: lstate.balance is no longer supported
    at web3.js:3690:28
    at web3.js:7206:23
    at web3.js:5966:44
    at <anonymous>:1:1

**Comment by vermaakash535** [comment]
use the -exchange param

Refer to https://wiki.sero.cash/en/index.html?file=Tutorial/sero-exchange-interface
