### ISSUE TITLE
Execute sero failed

### ISSUE THREAD

**Issue by rlinxy** [sero-cash/go-sero#6]
Version 0.7.1
Just downloaded the sero and execute, what I got is as below
What am I doing wrong? please advise

> github.com/sero-cash/go-czero-import/cpt.ZeroInit.func1(0xc000034ca0, 0x18, 0x2)
        /ext-go/1/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:58 +0x4c fp=0xc000057fc8 sp=0xc000057fa0 pc=0x577ecc
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000057fd0 sp=0xc000057fc8 pc=0x470571
created by github.com/sero-cash/go-czero-import/cpt.ZeroInit
        /ext-go/1/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:57 +0x52

goroutine 1 [chan receive]:
github.com/sero-cash/go-czero-import/cpt.ZeroInit(0xc000034ca0, 0x18, 0x2, 0x0, 0x41f900)
        /ext-go/1/src/github.com/sero-cash/go-czero-import/cpt/cpt.go:64 +0x6b
main.init.0.func1(0xc0000fc000, 0x15c9c50, 0xc0000ba4e0)
        /ext-go/1/src/github.com/sero-cash/go-sero/cmd/gero/main.go:214 +0x60e
github.com/sero-cash/go-sero/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc0000ba4e0, 0xc000098190, 0x1, 0x1, 0x0, 0x0)
        /ext-go/1/src/github.com/sero-cash/go-sero/vendor/gopkg.in/urfave/cli.v1/app.go:241 +0x6ce
main.main()
        /ext-go/1/src/github.com/sero-cash/go-sero/cmd/gero/main.go:338 +0xad

goroutine 20 [chan receive]:
github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc0000aa300, 0xc0000aa240)
        /ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:36 +0xb6
created by github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:29 +0xdc

goroutine 21 [chan receive]:
github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc0000aa300, 0xc0000aa2a0)
        /ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:81 +0x7b
created by github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify.newNonrecursiveTree
        /ext-go/1/src/github.com/sero-cash/go-sero/vendor/github.com/rjeczalik/notify/tree_nonrecursive.go:30 +0x108

goroutine 22 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

rax    0x0
rbx    0x25fb8c8
rcx    0x7fb35b522428
rdx    0x6
rdi    0x40e8
rsi    0x40e8
rbp    0x7fb35b8b2700
rsp    0x7ffde6506208
r8     0x7fb35b8b3770
r9     0x7fb35bef47c0
r10    0x8
r11    0x206
r12    0x25f9530
r13    0x25fb890
r14    0x7ffde6506470
r15    0x7ffde65066b0
rip    0x7fb35b522428
rflags 0x206
cs     0x33
fs     0x0
gs     0x0

**Comment by rlinxy** [comment]
start libczero ...


                         sssSSssss
                   sSSSSSSSSSSSSSSSSSSSs
               sSSSSSSSSSSSSSSSSSSSSSSSSSSs
             sSSSSSSss               ssSSSSSSs
          ssSSSSSSs        s sss        sSSSSSSs
         sSSSSSs     sSSSSSSSSSSSSSSs      sSSSSS
        sSSSS     +SSSSSSS+        sSSSsss   SSSSSs
      sSSSSs   sSSSSSSSs   sssSss      SSSS    sSSSS
      SSSS     SSSSSs     sSSSSSSSSs   sSSSSs   sSSSSs
    sSSSS    sSSSSSs     SSSSSSSSSSSs   SSSSSs    SSSSs
    SSSSs    SSSSSS     SSSSSSSSSSSSSs  SSSSSSSs   SSSS
   SSSSs    SSSSSSs    sSSSSSSSSSSSSSSs SSSSSSSSs  sSSSs
  sSSSs     SSSSSSs      SSSSSSSSSSSSSssSSSSSSSSSs  +SSSs
  SSSS      SSSSSSs      sSSSSSSSSS+SSSSSSSSSSSSSS  sSSSS
 sSSSs      SSSSSS         sSSSSSSSSSSsSSSSSSSSSSSs ssSSS
 sSSSs  s   SSSSSSs           SSSSSSSSSSssSSSSSSSSS   SSSs
 SSSS  sS    SSSSSSs             SSSSSSSSSs sSSSSSS   SSSs
 SSSss sSs   sSSSSSSs             ssSSSSSSSS  sSSSS   SSSs
 SSS+s SSS    sSSSSSSS               sSSSSSSS ssSSS   SSSS
 SSSSs sSSSs    sSSSSSSSss             sSSSSSSs SSS   SSSs
 SSSS  sSSSSS     SSSSSSSSSs            sSSSSSSs SS   SSS+
 SSSSs  SSSSSSS     sSSSSSSSSS            SSSSSs ss   SSSs
  SSS+  sSSSSSSSSSs   sSSSSSSSSSs         SSSSSS ss  +SSS
  SSSS   SSSSSSSSSSSss   sSSSSSSSs        sSSSSS    sSSSS
  sSSSs  sSSSSSSSs sSSSs   sSSSSSSs       SSSSSs    sSSSs
   SSSSs  sSSSSSSs  SSSSSSs sSSSSSSs      SSSSSs   sSSS+
    SSSS    SSSSS+   SSSSSSSssSSSSSs     sSSSS    sSSSS
    sSSSS    SSSSS   ssSSSSSSsSSSSss    sSSSSs    SSSS
      SSSSss   SSSs     SSSSSSSSSs     SSSSS    sSSSSs
       SSSSs    sSSs      +SSSSS     sSSSSs   ssSSSs
        sSSSSS    sSSSS           sSSSSs     SSSSSs
          SSSSS+ss     sSSSSSSSSSSSS      sSSSSSs
            SSSSSSss                   ssSSSSSSs
             sSSSSSSSsss           ssSSSSSSSS
                sSSSSSSSSSSSSSSSSSSSSSSSSSs
                   ssSSSSSSSSSSSSSSSSSs
                          rrssssrr


zero init ...
***CZERO*** nettype : 2
***CZERO*** b_path : /lib
***CZERO*** account_dir : /home/ray/.sero/keystore
load keypair from: /data/output
terminate called after throwing an instance of 'std::runtime_error'
  what():  load path failed: /data/output/vk.bin
SIGABRT: abort
PC=0x7f2439160428 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f2439160428
stack: frame={sp:0x7ffd3158cd38, fp:0x0} stack=[0x7ffd30d8f098,0x7ffd3158e0c0)
00007ffd3158cc38:  842d43bf6369b1ff  20fddadf107d20bc
00007ffd3158cc48:  0000002f4b6dc970  0000000000000000
00007ffd3158cc58:  0000000000000000  0000000000000000
00007ffd3158cc68:  0000000000000000  00000000000022b8
00007ffd3158cc78:  000000000000669f  0000000000009b58
00007ffd3158cc88:  0000000000019f24  0000000000022987
00007ffd3158cc98:  0000000000070e57  0000000000000000
00007ffd3158cca8:  0000000000000000  00000000000022b8
00007ffd3158ccb8:  000000000000669f  0000000000009b58
00007ffd3158ccc8:  0000000000019f24  0000000000022987
00007ffd3158ccd8:  0000000000070e57  0000000000000000
00007ffd3158cce8:  0000000000000000  0000000000000000
00007ffd3158ccf8:  0000000000000000  0000000000000002
00007ffd3158cd08:  0000000003c03628  00007f24394f0700
00007ffd3158cd18:  0000000003c01290  0000000003c035f0
00007ffd3158cd28:  00007ffd3158cfa0  00007ffd3158d1e0
00007ffd3158cd38: <00007f243916202a  0000000000000020
00007ffd3158cd48:  0000000000000000  0000000000000000
00007ffd3158cd58:  0000000000000000  0000000000000000
00007ffd3158cd68:  0000000000000000  0000000000000000
00007ffd3158cd78:  0000000000000000  0000000000000000
00007ffd3158cd88:  0000000000000000  0000000000000000
00007ffd3158cd98:  0000000000000000  0000000000000000
00007ffd3158cda8:  0000000000000000  0000000000000000
00007ffd3158cdb8:  0000000000000000  0000000000000000
00007ffd3158cdc8:  0000000000000000  0000000000000000
00007ffd3158cdd8:  0000000000000000  0000000000000000
00007ffd3158cde8:  0000000000000000  0000000000000000
00007ffd3158cdf8:  0000000000000000  0000000000000000
00007ffd3158ce08:  0000000000000000  0000000000000000
00007ffd3158ce18:  0000000000000000  0000000000000000
00007ffd3158ce28:  0000000000000000  0000000000000000
runtime: unknown pc 0x7f2439160428
stack: frame={sp:0x7ffd3158cd38, fp:0x0} stack=[0x7ffd30d8f098,0x7ffd3158e0c0)
00007ffd3158cc38:  842d43bf6369b1ff  20fddadf107d20bc
00007ffd3158cc48:  0000002f4b6dc970  0000000000000000
00007ffd3158cc58:  0000000000000000  0000000000000000
00007ffd3158cc68:  0000000000000000  00000000000022b8
00007ffd3158cc78:  000000000000669f  0000000000009b58
00007ffd3158cc88:  0000000000019f24  0000000000022987
00007ffd3158cc98:  0000000000070e57  0000000000000000
00007ffd3158cca8:  0000000000000000  00000000000022b8
00007ffd3158ccb8:  000000000000669f  0000000000009b58
00007ffd3158ccc8:  0000000000019f24  0000000000022987
00007ffd3158ccd8:  0000000000070e57  0000000000000000
00007ffd3158cce8:  0000000000000000  0000000000000000
00007ffd3158ccf8:  0000000000000000  0000000000000002
00007ffd3158cd08:  0000000003c03628  00007f24394f0700
00007ffd3158cd18:  0000000003c01290  0000000003c035f0
00007ffd3158cd28:  00007ffd3158cfa0  00007ffd3158d1e0
00007ffd3158cd38: <00007f243916202a  0000000000000020
00007ffd3158cd48:  0000000000000000  0000000000000000
00007ffd3158cd58:  0000000000000000  0000000000000000
00007ffd3158cd68:  0000000000000000  0000000000000000
00007ffd3158cd78:  0000000000000000  0000000000000000
00007ffd3158cd88:  0000000000000000  0000000000000000
00007ffd3158cd98:  0000000000000000  0000000000000000
00007ffd3158cda8:  0000000000000000  0000000000000000
00007ffd3158cdb8:  0000000000000000  0000000000000000
00007ffd3158cdc8:  0000000000000000  0000000000000000
00007ffd3158cdd8:  0000000000000000  0000000000000000
00007ffd3158cde8:  0000000000000000  0000000000000000
00007ffd3158cdf8:  0000000000000000  0000000000000000
00007ffd3158ce08:  0000000000000000  0000000000000000
00007ffd3158ce18:  0000000000000000  0000000000000000
00007ffd3158ce28:  0000000000000000  0000000000000000

**Comment by gordon-sero** [comment]
you must set env var $LD_LIBRARY_PATH to the path of ext-go/1/src/github.com/sero-cash/go-czero-import/lib_XXXXX  lib_XXXXX is the lib for your OS.
